### ISSUE TITLE
Why is CurrentHealth not an ObservableVariable?

### ISSUE THREAD

**Issue by irohiroki** [bzgeb/UnityUIDataBindingExample#1]
Hi,
I'm learning Unity and impressed of your blog post and how you organize objects. But I don't really understand why CurrentHealth of Health is not a ObservableVariable. It seems the dispatcher code (`OnHealthChanged?.Invoke`) is duplicated.

**Comment by bzgeb** [comment]
Hi! To be honest I don't remember. I don't see a reason why it shouldn't be. Perhaps I just forgot or copied it from another project?
